// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGSqAsoRikRI114HeqMLw9ZaH-QuqMzu4',
    appId: '1:666464155490:web:94d85658c49de1f3ef5e3b',
    messagingSenderId: '666464155490',
    projectId: 'iep-application-c22c6',
    authDomain: 'iep-application-c22c6.firebaseapp.com',
    storageBucket: 'iep-application-c22c6.firebasestorage.app',
    measurementId: 'G-BD6N1VGYVQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpvl9lryi1nqprAMch3UWMOJoNvAkOnRA',
    appId: '1:666464155490:android:6210a20ef1c41644ef5e3b',
    messagingSenderId: '666464155490',
    projectId: 'iep-application-c22c6',
    storageBucket: 'iep-application-c22c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApJ5FHFLyznkZJ4NB5Vvvb4iKzZOWOT-I',
    appId: '1:666464155490:ios:43da0124f85a007eef5e3b',
    messagingSenderId: '666464155490',
    projectId: 'iep-application-c22c6',
    storageBucket: 'iep-application-c22c6.firebasestorage.app',
    iosBundleId: 'com.example.iepApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApJ5FHFLyznkZJ4NB5Vvvb4iKzZOWOT-I',
    appId: '1:666464155490:ios:43da0124f85a007eef5e3b',
    messagingSenderId: '666464155490',
    projectId: 'iep-application-c22c6',
    storageBucket: 'iep-application-c22c6.firebasestorage.app',
    iosBundleId: 'com.example.iepApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGSqAsoRikRI114HeqMLw9ZaH-QuqMzu4',
    appId: '1:666464155490:web:756e9ced67db6789ef5e3b',
    messagingSenderId: '666464155490',
    projectId: 'iep-application-c22c6',
    authDomain: 'iep-application-c22c6.firebaseapp.com',
    storageBucket: 'iep-application-c22c6.firebasestorage.app',
    measurementId: 'G-WXJKG1G5GJ',
  );
}
